### ISSUE TITLE
Make problem

### ISSUE THREAD

**Issue by centurion800** [vadzimyatskevich/OrangePI_OLED#1]
Assembler messages:
Fatal error: can't create obj/example.o: No such file or directory
Makefile:15: recipe for target 'obj/example.o' failed
make: *** [obj/example.o] Error 1

Linux orangepizero 3.4.113-sun8i

**Comment by vadzimyatskevich** [comment]
Compiler tries to create "obj/example.o" but "obj" folder doesn't exist. Just create "obj" directory.
Repository updated.
