### ISSUE TITLE
make problem :)

### ISSUE THREAD

**Issue by centurion800** [vadzimyatskevich/OrangePI_OLED#2]
/usr/bin/ld: cannot open output file build/OrangePI_ssd1306: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'build/OrangePI_ssd1306' failed
make: *** [build/OrangePI_ssd1306] Error 1

**Comment by vadzimyatskevich** [comment]
OK then :) and hope you know what to do. I've created folder in repository, try to clone and build again. report result please,  now I have no board to test.

**Comment by centurion800** [comment]
obj/example.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'build/OrangePI_ssd1306' failed
make: *** [build/OrangePI_ssd1306] Error 1

**Comment by vadzimyatskevich** [comment]
Let's try again. Remove, clone, build and report, later I will try it on clean image.

**Comment by centurion800** [comment]
done. all work fine. thnks!!

**Comment by centurion800** [comment]
How i can add wifi signal strength meter?

**Comment by vadzimyatskevich** [comment]
Of course you can, but by writing this function. I'm currently not planning to develop this project.
