### ISSUE TITLE
128x32 OLED

### ISSUE THREAD

**Issue by One-Phantom** [vadzimyatskevich/OrangePI_OLED#3]
Hi,
I'm trying to use it with the 128x32 Oled, removing the IP infos (saving a couple of lines)
Where should I look?

Thanks.

**Comment by vadzimyatskevich** [comment]
just comment lines 144-189 in example.c

**Comment by One-Phantom** [comment]
Thanks. 
It worked, but I cannot get the right resolution. When I change SSD1306_LCDHEIGHT to 32, Text and graphics only take a quarter of the all display (unreadable).

**Comment by vadzimyatskevich** [comment]
Unfortunately I have only 128x64 display to test. SSD1306_LCDHEIGHT is used to determine buffer size and in ssd1306DrawPixel() to see if pixel visible. 

I can assume that some modifications needed in init function. Try to change line 101     ssd1306Command(   0x12) to ssd1306_command(0x02) in ssd1306.c

**Comment by One-Phantom** [comment]
You were right, thanks.
Now it works very well.
