### ISSUE TITLE
Code deleted?

### ISSUE THREAD

**Issue by marcoamr2002** [vadzimyatskevich/OrangePI_OLED#4]
Please, can you share the code again? It will be very usefull to me

Thanks in advance

Kind Regards

**Comment by vadzimyatskevich** [comment]
Use command  `git clone https://github.com/vadzimyatskevich/SSD1306.git` just checked everything works fine and code on it's place.

**Comment by marcoamr2002** [comment]
Thank you very much.
When i try to run ./build/OrangePI_ssd1306 I get this error:
My pid is: 973
Failed to open the bus.

This is a Orange Pi Zero, what can I do?

**Comment by vadzimyatskevich** [comment]
Do you run it with superuser privileges?
