### ISSUE TITLE
Current kernel.

### ISSUE THREAD

**Issue by tothb001** [vadzimyatskevich/OrangePI_OLED#5]
Hi!  The current kernel also works.  The only problem is that the cpu temperature is long.  The cpu temperature source is not xx ° C but xxxxx ° C.  I think you have decimals.  What can be done?

**Comment by anITiot** [comment]
Working nearly as expected on Armbian Bionic OPi Zero 512mb:
[SSD1306_opi0_armbianBionic.txt](https://github.com/vadzimyatskevich/SSD1306/files/4134722/SSD1306_opi0_armbianBionic.txt)
Maybe the libs are changed in the new kernel version but I'm an (to)old C-beginner....

But now I know that ssd1306 works on this SBC :)

**Comment by tothb001** [comment]
Hi! Thank you very much for your reply.  I'm a very beginner c-programmer.  And my English is not good either.  I couldn't find a solution to this problem.  Thanks for the help.

**Comment by vadzimyatskevich** [comment]
https://github.com/vadzimyatskevich/SSD1306/commit/9437543a3812b6952b9304c9d9334fb30040e11b
